import os

RPC_URL = os.environ.get("SOLANA_RPC_URL", "https://api.mainnet-beta.solana.com")
KEYPAIR_PATH = "./keypair.json"

TRADE_PCT       = float(os.environ.get("TRADE_PCT", "0.30"))
GAS_RESERVE_SOL = float(os.environ.get("GAS_RESERVE_SOL", "0.05"))
MIN_TRADE_SOL   = 0.01

MONITOR_BC_MIN      = 1
MONITOR_BC_MAX      = 88
MOMENTUM_WINDOW_SEC = 10
MIN_BC_RISE_PCT     = 2

PROFIT_TARGET_PCT = 20
STOP_LOSS_PCT     = 7
MAX_HOLD_SECONDS  = 60

TRAIL_ACTIVATE_PCT = 5
TRAIL_DRAWDOWN_PCT = 5

POLL_INTERVAL_SEC = 2.0

SLIPPAGE_BPS = 300
PRIORITY_FEE = "auto"
GAS_COST_ROUNDTRIP_SOL = float(os.environ.get("GAS_COST_ROUNDTRIP_SOL", "0.003"))

SOL_MINT  = "So11111111111111111111111111111111111111112"
USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

PARK_PROFITS = True
PARK_AS_USDC = False

MAX_CREATOR_COINS   = 4
MIN_REPLY_COUNT     = 0
MIN_AGE_SECONDS     = 90
COPY_SIMILARITY_PCT = 80
